-- pcm: sampled sound effects on TIC-80 1.2's PCM channel, played straight out
-- of the <MAP> region. The engine has ONE PCM channel (128 unsigned bytes per
-- frame at 0x14e24, 7,680 Hz), so this module owns it outright and every effect
-- goes through here -- two modules poking that buffer would overwrite each
-- other, and per-effect silence midpoints would thump at each handover.
--
-- Wiring, in the entry stub (main.lua): TIC() calls pcm.update() every frame,
-- idle ones and the boot intro included. Callers use pcm.play("<name>"), which
-- returns false when the sample cannot sound now -- see fire_sound() in
-- sfx.lua, which falls back to the SFX slot on that false.
--
-- THE SAMPLE BYTES ARE NOT IN THIS FILE. They live in the cart's <MAP> region
-- at `base` below, so they cost the code budget nothing and no decode runs at
-- load; `bank` is only the {offset, length} index into that region. Both are
-- generated -- `python tools/build.py patch pcm` rebuilds the bytes AND prints
-- the index to copy here. The layout, the regeneration command and the
-- don't-draw-here warning live with the data: docs/map-data-block.md.
--
-- PCM is a sample plus this playback code, NOT an SFX-editor instrument. It
-- leaves all four synthesizer channels free. Bandwidth stops at ~3.8 kHz, so a
-- sample is not bit-exact to its source recording.

pcm = {}

local ADDR = 0x14e24   -- the engine's PCM buffer, 128 bytes consumed per frame
local BLOCK = 128

-- Generated by `tools/build.py patch pcm` -- keep in step with the <MAP> bytes.
local base = 0x0AA00   -- where the bank sits in the MAP region
local midpoint = 47    -- the one silence level shared by every sample
local bank = {
 fire = {0, 2336},     -- {offset from base, length in bytes}
}

local position = nil   -- next byte offset within the bank, nil = idle
local remaining = 0    -- bytes left of the playing sample
local gain = 1
local warmup = 0       -- frames of midpoint ramp-in; playback waits for 30
local from = 0         -- DC level the ramp starts at (see update())
local supported = nil  -- nil until probed, then true/false
local probed = 0

-- true once the engine is confirmed to have a PCM channel AND the bank is
-- switched on. TIC-80 1.2+ clears the PCM buffer before every TIC; 1.1 and
-- older leave that reserved RAM as we left it. So update() writes a marker byte
-- on its first call and reads it back on the second -- which is why this only
-- settles from frame 2 onward.
--
-- `pcm_enabled=false` in constants.lua forces this false on any engine, which
-- sends every caller down its SFX fallback: that is how the pre-1.2 sound is
-- auditioned on a 1.2 machine (see README "Sampled effects").
function pcm.ok() return supported == true end

-- true once the midpoint ramp has finished and a play() would sound at once
function pcm.ready() return supported == true and warmup >= 30 end

-- true while a sample is still sounding
function pcm.playing() return position ~= nil end

-- (re)trigger a named sample from the start. volume 0..1 scales around the
-- silence midpoint; the bank is already normalized to its unclipped maximum,
-- so >1 would clip the peaks.
--
-- Returns false when the sample cannot sound NOW, so the caller can fall back
-- to an SFX slot rather than lose the cue: that covers an engine with no PCM
-- channel, an unknown name, and the first 30 frames while the midpoint is still
-- ramping in (a cue arriving half a second late would be worse than an SFX one).
function pcm.play(name, volume)
 local s = bank[name]
 if not s or not pcm.ready() then return false end
 gain = math.max(0, math.min(1, volume or 1))
 position, remaining = s[1], s[2]
 return true
end

-- cut the playing sample; update() keeps writing the silence midpoint
function pcm.stop() position = nil remaining = 0 end

-- Call EXACTLY once per TIC, including idle frames and after stop(): the engine
-- clears the buffer each frame, so silence has to be written as the steady
-- midpoint or the DC level steps and thumps.
function pcm.update()
 if supported == nil then
  -- Switched off in constants.lua: never probe, never touch the buffer. The
  -- engine's own silence stands, exactly as on a machine with no PCM channel.
  if not pcm_enabled then supported = false return end
  probed = probed + 1
  if probed == 1 then
   poke(ADDR + BLOCK - 1, 0xff) -- the marker 1.2 clears and 1.1 leaves alone
   return
  end
  supported = peek(ADDR + BLOCK - 1) == 0
  if not supported then return end
 elseif supported == false then
  return
 end
 -- Ramp to the midpoint over 30 frames, FROM the level the channel is already
 -- sitting at rather than from zero. Cold that is 0 and this is the original
 -- ramp-in; after the Apple II intro (a2boot.lua) it is that module's own
 -- silence level, and starting there glides the two baselines together instead
 -- of stepping down and thumping at the handover.
 if warmup == 0 then from = peek(ADDR) end
 warmup = math.min(30, warmup + 1)
 local silence = math.floor(from + (midpoint - from) * warmup / 30 + 0.5)
 for i = 0, BLOCK - 1 do
  local value = silence
  if warmup >= 30 and position then
   value = math.floor(midpoint + (peek(base + position) - midpoint) * gain + 0.5)
   position, remaining = position + 1, remaining - 1
   if remaining <= 0 then position = nil end
  end
  poke(ADDR + i, value)
 end
end
