-- sfx: the 16-slot SFX bank (README "Sound effects"; chunks mastered in
-- main.lua, generated by tools/build.py from the original's speaker bytecode).
-- The slot ids themselves (sfx_fire, sfx_chopper, ...) live in constants.lua
-- with the rest of the port's named constants; this module owns the playback
-- wiring. Music (the 11 songs) plays from the <PATTERNS>/<TRACKS> chunks via
-- play_song/song_stop/music_playing; the bonus tick (song 10) is not a track --
-- the design maps it onto the blip.
--
-- Channels: 0 general one-shots, 1 heli-gunfire reports, 2 chopper drone,
-- 3 player (hit + sink) - the PICO-8 port's channel budget carried over.

-- play length per one-shot slot in 60Hz frames (from the generator report;
-- envelopes end silent, so the exact value only stops channel occupation)
local dur = {[0] = 18, [2] = 10, [3] = 3, [4] = 29, [5] = 3, [6] = 27,
             [7] = 8, [8] = 21, [9] = 10, [10] = 10, [11] = 5, [12] = 8,
             [14] = 19, [15] = 2, [16] = 17}

-- One-shot channel allocation. PICO-8's sfx(n,-1) picked any free channel,
-- so overlapping effects coexisted; TIC-80 has no auto-allocation, and
-- pinning every one-shot to ch0 made each missile shot CUT the explosion
-- still playing there. psfx therefore tracks when each channel falls idle
-- and picks a free one: ch0 first, then 3 and 2 when no drone owns them
-- (ch1 stays the gunfire's). An explicit ch argument bypasses the search
-- (the player's own sounds always preempt ch3, like the original's ch E).
local busy = {[0] = 0, [2] = 0, [3] = 0}
loop_on = {} -- [ch] = true while a drone loop owns the channel

-- one-shot effect; the demo guard keeps the attract demo silent.
-- NOTE the nil note: an INTEGER note argument always overrides the slot's
-- baked note - even -1, which the Lua binding turns into note -1/octave 0
-- (~16 Hz, i.e. scratchy clicks). Only nil/omitted means "stored default".
function psfx(id, ch)
 if demo then return end
 if not ch then
  ch = 0
  local now = time()
  for _, c in ipairs{0, 3, 2} do
   if not loop_on[c] and now >= busy[c] then
    ch = c
    break
   end
  end
 end
 sfx(id, nil, dur[id], ch)
 if busy[ch] then busy[ch] = time() + dur[id] * 16.7 end
end

-- player missile launch. Slot 0's 8-wavetable fit is a close but band-limited
-- approximation of the recording; on TIC-80 1.2+ the same recording plays as a
-- 7,680 Hz sample on the PCM channel instead (pcm.lua), which keeps the burst
-- timing and attack detail the SFX fit loses. The PCM channel is separate from
-- the four synth channels, so the shot no longer competes with explosions for
-- a one-shot channel either. Older engines have no such channel and fall back
-- to the slot, so both stay shipped and slot 0 must not be repurposed.
function fire_sound()
 if demo then return end
 if not pcm.play("fire") then psfx(sfx_fire) end
end

-- looping drone (chopper, sink): no duration, so the slot's envelope loop
-- sustains until the channel is explicitly stopped
function lsfx(id, ch)
 if demo then return end
 sfx(id, nil, -1, ch)
 loop_on[ch] = true
end

-- silence channel ch and release any drone loop that owned it
function sfx_stop(ch)
 sfx(-1, nil, nil, ch)
 loop_on[ch] = nil
end

-- chopper rotor: loop on ch2 while any heli is mid-dive (the original's
-- SNDSCAN re-queues ch1 per frame; here an edge-managed loop)
function chopper_sound()
 local on = false
 if ens and not demo then
  for _, e in ipairs(ens) do
   if e.heli and e.st == 3 then
    on = true
    break
   end
  end
 end
 if on and not loop_on[2] then
  lsfx(sfx_chopper, 2)
 elseif not on and loop_on[2] then
  sfx_stop(2)
 end
end

-- heli gunfire: ONE report per round, exactly the original's model - its
-- round spawner ($0F99) restarts ch1's 12 ms three-burst 3055 Hz report on
-- every round. Slot 15 is that report as a single 16.7 ms envelope tick
-- (dur 2). Nothing is looped, so there is nothing to stop on a kill or a
-- play exit (docs/sound-effects.md "Heli fire").
--
-- EVERY ROUND IS HEARD. A round is QUEUED, never dropped, and the queue is
-- drained one report per display frame (hf_pull below, called from TIC): four
-- rounds always give four blips. Two things forced this:
--
--  * Rounds inside a string land 1 OR 2 oticks apart (measured: gaps of 53
--    and 107 ms). A same-channel sfx() RESTARTS the slot, so two rounds in
--    the same frame - or a second one before the 33 ms report has finished -
--    merge into a single audible blip. That is the "fires four shots, I hear
--    two blips" report.
--  * A minimum-gap filter (the previous fix) is the wrong tool: it makes the
--    count of blips depend on timing, which is precisely what must not vary.
--    It also silently dropped nearly everything under a headless clock.
--
-- hf_gap_f (constants.lua) is the knob: display frames between consecutive
-- reports, so it sets the rattle's spacing WITHOUT ever changing the count.
-- The original's frame period sagged to ~70-90 ms while a heli dove (the
-- video's reports sit ~90 ms apart), which is why the default spaces rounds
-- wider than the sim's own 53 ms otick.
local hf_queue, hf_wait = 0, 0

-- queue one heli-gunfire report (played later by hf_pull)
function heli_fire_round()
 if demo then return end
 hf_queue = hf_queue + 1 -- queued, never dropped: one blip per round
end

-- drain the gunfire queue, once per DISPLAY frame (main.lua TIC). Frame-based
-- rather than wall-clock so a slow or headless frame cannot merge two reports.
function hf_pull()
 if hf_wait > 0 then hf_wait = hf_wait - 1 end
 if hf_queue > 0 and hf_wait <= 0 then
  hf_queue = hf_queue - 1
  hf_wait = hf_gap_f
  psfx(sfx_helifire, 1)
 end
end

-- drop any rounds still queued (leaving play, a wave ending, a death): the
-- shots they belonged to are gone, so their reports should not trail after.
function hf_clear()
 hf_queue, hf_wait = 0, 0
end

-- music: the original's 11 songs (9 wave jingles + dirge + bonus tick),
-- decoded from the $B600 [dur,p1,p2] triplets by tools/build.py (`patch
-- music`) into tracker patterns - FULL length (the PICO-8 port trimmed
-- waves 5/8/9 to fit its sfx bank; the tracker fits them whole). Song 10,
-- the bonus tick, stays the blip SFX. Voices ride ch1/ch2 so ch0/ch3 stay
-- free for game SFX (README "Music").
--
-- Ten songs share TIC-80's 8 track slots: wave3+wave5 pair up in track 2
-- and wave4+dirge in track 3, the second song starting at a later frame,
-- with an EMPTY frame between them: loop=false playback stops by itself at
-- the first all-empty frame (sound.c), so no song ever runs into its
-- neighbor. music_playing() reads the engine's own position registers
-- ($13FFC track/frame/row) rather than a wall-clock timer - the tracker
-- advances one row per TIC() call, so on a display that isn't exactly 60 Hz
-- music time and time() drift apart and a timer cuts songs off early (the
-- first shipped version's bug). song_rowend = the absolute track row where
-- each song's stream ends, stopping a pair-first before it idles through
-- its last pattern's silent tail. (Tables from `build.py patch music`.)
song_trk = {0, 1, 2, 3, 2, 4, 5, 6, 7, 3}
song_frame = {0, 0, 0, 0, 4, 0, 0, 0, 0, 3}
song_rowend = {76, 68, 186, 104, 508, 124, 288, 100, 198, 236}
-- song titles by song id (shown on the wave-clear screen while the jingle plays)
song_names = {
 "SHAVE AND A HAIRCUT", "DRUNKEN SAILOR", "POPEYE THE SAILOR MAN",
 "ROW, ROW, ROW YOUR BOAT", "SPANISH LADIES", "PAY ME MY MONEY DOWN",
 "MY BONNIE LIES OVER THE OCEAN", "BLOW THE MAN DOWN",
 "A SAILOR WENT TO SEA", "FLEET SUNK DIRGE"}
local cur_song = nil

-- start song id (0-9 from the tracker; 10 is the bonus-tick blip)
function play_song(id)
 if demo then return end
 if id == 10 then -- bonus tick: the blip, on ch0 (never a music channel)
  psfx(sfx_blip)
  return
 end
 sfx_stop(1) -- the jingle channels; any gunfire/chopper loop is stale here
 sfx_stop(2)
 music(song_trk[id + 1], song_frame[id + 1], 0, false)
 cur_song = id
end

-- stop the music now
function song_stop()
 music()
 cur_song = nil
end

-- true while the current song is still playing (read from the engine's
-- position registers; stops the song at its exact end row)
function music_playing()
 if not cur_song then return false end
 if peek(0x13FFC) ~= song_trk[cur_song + 1] then
  cur_song = nil -- the engine stopped itself (empty frame / track end)
  return false
 end
 local pos = peek(0x13FFD) * 64 + peek(0x13FFE)
 if pos >= song_rowend[cur_song + 1] then
  song_stop() -- exact stream end: skip the final pattern's silent tail
  return false
 end
 return true
end
